In [1]:
import numpy as np


In [2]:
p1 = np.array([1,1])
p2 = np.array([4,4])


In [4]:
p2 - p1

array([ 2.9,  2.9])

In [5]:
p1



array([ 1.1])

In [6]:
p1 = np.array([1,1])


In [7]:
p2 - p1


array([3, 3])

In [9]:
np.power(p2 - p1, 2)

array([9, 9])

In [10]:
import numpy as np

def distance(p1, p2):
    """ Finds the distance between points p1 and p2."""
    return np.sqrt(np.sum(np.power(p2 - p1, 2)))

p1 = np.array([1,1])
p2 = np.array([4,4])
distance(p1, p2)

4.2426406871192848

In [23]:
def majority_vote(votes):
    """
    xxx
    """
          
    vote_counts = {}
    for vote in votes:
        if vote in vote_counts:
            vote_counts[vote] += 1
        else:
            vote_counts[vote] = 1
    return vote_counts

votes = [1,2,3,1,2,3,3,3,3,1,2,3]
vote_counts = majority_vote(votes)

In [17]:
vote_counts


{1: 3, 2: 3, 3: 6}

In [18]:
max(vote_counts)

3

In [20]:
max(vote_counts.values())

6

In [27]:
max_count = max(vote_counts.values())

In [28]:
def majority_vote(votes):
    """
    xxx
    """
          
    vote_counts = {}
    for vote in votes:
        if vote in vote_counts:
            vote_counts[vote] += 1
        else:
            vote_counts[vote] = 1
    return vote_counts

votes = [1,2,3,1,2,3,3,3,3,1,2,3]
vote_counts = majority_vote(votes)

max_count = max(vote_counts.values()) ## from line 21

for vote, count in vote_counts.items():
    print(vote, count)

1 3
2 3
3 6


In [29]:
def majority_vote(votes):
    """
    xxx
    """
          
    vote_counts = {}
    for vote in votes:
        if vote in vote_counts:
            vote_counts[vote] += 1
        else:
            vote_counts[vote] = 1
    return vote_counts

votes = [1,2,3,1,2,3,3,3,3,1,2,3]
vote_counts = majority_vote(votes)

winners = []
max_count = max(vote_counts.values()) ## from line 21
for vote, count in vote_counts.items():
    if count == max_count:
        winners.append(vote)
    print(vote, count)
    


1 3
2 3
3 6


In [30]:
winners

[3]

In [37]:
import random

def majority_vote(votes):
    """
     return the most common element in votes.
    """
          
    vote_counts = {}
    for vote in votes:
        if vote in vote_counts:
            vote_counts[vote] += 1
        else:
            vote_counts[vote] = 1

    winners = []
    max_count = max(vote_counts.values()) ## from line 21
    for vote, count in vote_counts.items():
        if count == max_count:
            winners.append(vote)
            
    return random.choice(winners)

votes = [1,2,3,1,2,3,3,3,3,1,2,3,2,2,2,2,2]
winner = majority_vote(votes)
    


In [38]:
winner

2

Stop for tonight. pick up at 8:46 video 3.3.3.

In [4]:
import scipy.stats as ss

def majority_vote_short(votes):
    """
    return the most common element in votes.
    """
    mode, count = ss.mstats.mode(votes)
    return mode

votes = [1,2,3,1,2,3,3,3,3,1,2,3,2,2,2,2,2]
winner = majority_vote_short(votes)

In [5]:
winner

array([ 2.])

Nearest Neighbors, again
    

In [16]:
# loop over all points
    #compute distance bw point p and every other point
# sort distances and return those k points that are nearest to point p
import numpy as np
import matplotlib.pyplot as plt

distances = np.zeros(points.shape[0])
for i in range(len(distances)):
    distances[i] = distance(p, points[i])
    
points = np.array([[1,1],[1,2],[1,3],[2,1],[2,2],[2,3],[3,1],[3,2],[3,3]])
p = np.array([2.5, 2])


plt.plot(points[:,0], points[:,1], "ro")
plt.plot(p[0], p[1], "bo")
plt.axis([0.5], [3.5], [0.5], [3.5])

NameError: name 'distance' is not defined

why won't Jupyter let me call distance()? 'distance' is not defined-- should it be imported by another module?
