In [1]:
import numpy as np


In [2]:
p1 = np.array([1,1])
p2 = np.array([4,4])


In [4]:
p2 - p1

array([ 2.9,  2.9])

In [5]:
p1



array([ 1.1])

In [6]:
p1 = np.array([1,1])


In [7]:
p2 - p1


array([3, 3])

In [9]:
np.power(p2 - p1, 2)

array([9, 9])

In [10]:
import numpy as np

def distance(p1, p2):
    """ Finds the distance between points p1 and p2."""
    return np.sqrt(np.sum(np.power(p2 - p1, 2)))

p1 = np.array([1,1])
p2 = np.array([4,4])
distance(p1, p2)

4.2426406871192848